Fly
es un Plugin de vuelo para PocketMine-MP que le permite volar en modo de supervivencia cuando ejecuta el comando de vuelo.

Este complemento sería útil para servidores grandes o skyblock a los que no les gustaría que los jugadores usen fly en zonas PVP o en el hub. Y si desea que los jugadores paguen por cambiar de vuelo, ¡hay una opción para eso!

Permisos:
fly.command.use

Pokker77#0282 Por Cualquier Bug